#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
canonical_root="/Users/bensuo/ghostty-codex-launchpad"
canonical_prompt_source="$canonical_root/prompts/prompt-source.sh"
canonical_launcher="$canonical_root/git-ghostty-codex-launchpad.sh"

tmp_contract="$(mktemp -t codex-prompt-contract.XXXXXX)"
tmp_actual="$(mktemp -t codex-prompt-actual.XXXXXX)"
trap 'rm -f "$tmp_contract" "$tmp_actual"' EXIT

render_contract_doc() {
  cat > "$1" <<'EOF'
# Generated Prompts

Source: `docs/prompt-source.md`

This file is generated by `scripts/render-prompt-docs.sh`.
Edit the source file, then re-run the generator.

EOF

  cat "$project_root/docs/prompt-source.md" >> "$1"
}

strip_role_wrapper() {
  awk 'blank_count >= 2 { print; next } /^$/ { blank_count++; next }'
}

render_actual_doc() {
  source "$canonical_prompt_source"
  source "$canonical_launcher"

  cat > "$1" <<'EOF'
# Generated Prompts

Source: `docs/prompt-source.md`

This file is generated by `scripts/render-prompt-docs.sh`.
Edit the source file, then re-run the generator.

# Prompt Source

This file is the canonical prompt source for this duplicate workflow repo.

Goal:
- Keep the launcher wrapper thin.
- Keep shared behavior in `AGENTS.md` and the shared artifact.
- Keep role blocks limited to role-specific delta only.

## Base Wrapper

```text
EOF

  base_wrapper_prompt "{ROLE}" "{PROJECT_NAME}" "{PROJECT_DIR}" "{TARGET_FILE}" "{SHARED_CONTEXT_FILE}" >> "$1"

  cat >> "$1" <<'EOF'
```

Notes:
- Shared fallback behavior should live in the shared artifact instead of the wrapper when possible.
- Response format should come from the shared artifact, not the base wrapper.
- If `/clear` resets the session, re-inject the same terminal-local project facts before the next role prompt.

## Roles

### BUILDER

```text
EOF

  role_prompt "BUILDER" "{PROJECT_NAME}" "{PROJECT_DIR}" "{TARGET_FILE}" "{SHARED_CONTEXT_FILE}" \
    | strip_role_wrapper >> "$1"

  cat >> "$1" <<'EOF'
```

### BACKEND

```text
EOF

  role_prompt "BACKEND" "{PROJECT_NAME}" "{PROJECT_DIR}" "{TARGET_FILE}" "{SHARED_CONTEXT_FILE}" \
    | strip_role_wrapper >> "$1"

  cat >> "$1" <<'EOF'
```

### CRITIC

```text
EOF

  role_prompt "CRITIC" "{PROJECT_NAME}" "{PROJECT_DIR}" "{TARGET_FILE}" "{SHARED_CONTEXT_FILE}" \
    | strip_role_wrapper >> "$1"

  cat >> "$1" <<'EOF'
```

### DEBUGGER

```text
EOF

  role_prompt "DEBUGGER" "{PROJECT_NAME}" "{PROJECT_DIR}" "{TARGET_FILE}" "{SHARED_CONTEXT_FILE}" \
    | strip_role_wrapper >> "$1"

  cat >> "$1" <<'EOF'
```
EOF
}

[ -f "$canonical_prompt_source" ] || {
  echo "Missing canonical prompt source: $canonical_prompt_source" >&2
  exit 1
}

[ -f "$canonical_launcher" ] || {
  echo "Missing canonical launcher: $canonical_launcher" >&2
  exit 1
}

render_contract_doc "$tmp_contract"

if ! diff -u "$project_root/docs/generated-prompts.md" "$tmp_contract" >/dev/null; then
  echo "Prompt docs are out of date with docs/prompt-source.md. Re-run scripts/render-prompt-docs.sh." >&2
  diff -u "$project_root/docs/generated-prompts.md" "$tmp_contract" >&2 || true
  exit 1
fi

render_actual_doc "$tmp_actual"

if ! diff -u "$tmp_contract" "$tmp_actual" >/dev/null; then
  echo "Prompt drift detected: canonical launcher output no longer matches docs/prompt-source.md." >&2
  diff -u "$tmp_contract" "$tmp_actual" >&2 || true
  exit 1
fi

echo "Prompt drift check passed."
