#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
source_file="$project_root/docs/prompt-source.md"
agents_file="$project_root/AGENTS.md"
output_file="$project_root/docs/generated-launcher-contract.md"

extract_section() {
  local heading=$1
  awk -v heading="$heading" '
    $0 == heading { printing=1; next }
    /^## / && printing { exit }
    printing { print }
  ' "$agents_file"
}

extract_role_ownership() {
  local role=$1
  perl -0ne '
    my $role = $ENV{ROLE_NAME};
    if (m/^### \Q$role\E\s+```text\n.*?\n(Owns:\n.*?)(?:\nMust:)/ms) {
      print $1;
    }
  ' "$source_file"
}

cat > "$output_file" <<EOF
# Generated Launcher Contract

Source files:
- \`docs/prompt-source.md\`
- \`AGENTS.md\`

This file is generated by \`scripts/render-launcher-contract.sh\`.
Edit the source files, then re-run the generator.

## Wrapper

\`\`\`text
$(awk '
  /^```text$/ { in_block=1; next }
  /^```$/ && in_block { exit }
  in_block { print }
' "$source_file")
\`\`\`

## Role List

- \`BUILDER\`
- \`BACKEND\`
- \`CRITIC\`
- \`DEBUGGER\`

## Artifact Ownership

### BUILDER

$(ROLE_NAME="BUILDER" extract_role_ownership "BUILDER")

### BACKEND

$(ROLE_NAME="BACKEND" extract_role_ownership "BACKEND")

### CRITIC

$(ROLE_NAME="CRITIC" extract_role_ownership "CRITIC")

### DEBUGGER

$(ROLE_NAME="DEBUGGER" extract_role_ownership "DEBUGGER")

## Commit Rules

$(extract_section "## Commit Rules")

## Publish Rules

$(extract_section "## Publish Rules")
EOF
