#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
source_file="$project_root/docs/prompt-source.md"
output_file="$project_root/docs/generated-prompts.md"

cat > "$output_file" <<EOF
# Generated Prompts

Source: \`docs/prompt-source.md\`

This file is generated by \`scripts/render-prompt-docs.sh\`.
Edit the source file, then re-run the generator.

EOF

cat "$source_file" >> "$output_file"

bash "$project_root/scripts/render-launcher-contract.sh"
