#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

source "$project_root/prompts/prompt-source.sh"
source "$project_root/git-ghostty-codex-launchpad.sh"

tmp_generated="$(mktemp -t codex-prompt-generated.XXXXXX)"
tmp_expected="$(mktemp -t codex-prompt-expected.XXXXXX)"
tmp_actual="$(mktemp -t codex-prompt-actual.XXXXXX)"
trap 'rm -f "$tmp_generated" "$tmp_expected" "$tmp_actual"' EXIT

cat > "$tmp_generated" <<'EOF'
# Generated Prompts

Source: `prompts/prompt-source.sh`

This file is generated by `scripts/render-prompt-docs.sh`.
Edit the prompt source, then rerun the generator.

## Base Wrapper

```text
EOF

base_wrapper_prompt "{ROLE}" "{PROJECT_NAME}" "{PROJECT_DIR}" "{TARGET_FILE}" "{SHARED_CONTEXT_FILE}" >> "$tmp_generated"

cat >> "$tmp_generated" <<'EOF'
```

## BUILDER

```text
EOF

role_prompt_body "BUILDER" >> "$tmp_generated"

cat >> "$tmp_generated" <<'EOF'
```

## BACKEND

```text
EOF

role_prompt_body "BACKEND" >> "$tmp_generated"

cat >> "$tmp_generated" <<'EOF'
```

## CRITIC

```text
EOF

role_prompt_body "CRITIC" >> "$tmp_generated"

cat >> "$tmp_generated" <<'EOF'
```

## DEBUGGER

```text
EOF

role_prompt_body "DEBUGGER" >> "$tmp_generated"

cat >> "$tmp_generated" <<'EOF'
```
EOF

if ! diff -u "$project_root/docs/generated-prompts.md" "$tmp_generated" >/dev/null; then
  echo "Generated prompt docs are out of date. Re-run scripts/render-prompt-docs.sh." >&2
  exit 1
fi

for role in BUILDER BACKEND CRITIC DEBUGGER; do
  {
    base_wrapper_prompt "$role" "Project" "/tmp/project" "README.md" "/tmp/shared.md"
    printf '\n'
    role_prompt_body "$role"
  } > "$tmp_expected"

  role_prompt "$role" "Project" "/tmp/project" "README.md" "/tmp/shared.md" > "$tmp_actual"

  if ! diff -u "$tmp_expected" "$tmp_actual" >/dev/null; then
    echo "Prompt drift detected for role $role." >&2
    diff -u "$tmp_expected" "$tmp_actual" >&2 || true
    exit 1
  fi
done

echo "Prompt drift check passed."
