#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
source "$project_root/prompts/prompt-source.sh"

output_file="$project_root/docs/generated-prompts.md"
role_selection_file="$project_root/docs/role-selection.md"

cat > "$output_file" <<'EOF'
# Generated Prompts

Source: `prompts/prompt-source.sh`

This file is generated by `scripts/render-prompt-docs.sh`.
Edit the prompt source, then rerun the generator.

## Base Wrapper

```text
EOF

base_wrapper_prompt "{ROLE}" "{PROJECT_NAME}" "{PROJECT_DIR}" "{TARGET_FILE}" "{SHARED_CONTEXT_FILE}" >> "$output_file"

cat >> "$output_file" <<'EOF'
```

## BUILDER

```text
EOF

role_prompt_body "BUILDER" >> "$output_file"

cat >> "$output_file" <<'EOF'
```

## BACKEND

```text
EOF

role_prompt_body "BACKEND" >> "$output_file"

cat >> "$output_file" <<'EOF'
```

## CRITIC

```text
EOF

role_prompt_body "CRITIC" >> "$output_file"

cat >> "$output_file" <<'EOF'
```

## DEBUGGER

```text
EOF

role_prompt_body "DEBUGGER" >> "$output_file"

cat >> "$output_file" <<'EOF'
```
EOF

role_selection_summary > "$role_selection_file"
